In [1]:
import os
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from networks.model import TD3_Actor
from environment.env import TradingEnv
from pykalman import KalmanFilter
from sklearn.preprocessing import MinMaxScaler
from environment.wrappers import env_wrapper
import matplotlib.pyplot as plt
from scipy.special import softmax

g:\Code\Python\GitHub\Portfolio-Optimizer\.venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [22]:
test = np.array([3, 1])
test_1 = np.array([4, 1])
np.concatenate([test, test_1])

array([3, 1, 4, 1])

In [20]:
test / test[0, -1]

array([[[0.79401137, 1.1442475 , 1.88476997, 2.9387764 ],
        [0.55904318, 1.29927868, 1.69766974, 0.26191503],
        [1.30524131, 0.15427702, 0.16971658, 1.93649807],
        [1.04078574, 1.39597516, 1.08558159, 1.43830296],
        [0.1835339 , 0.95206068, 1.349897  , 0.04074164],
        [0.45299555, 0.93542293, 3.32338026, 2.97546933],
        [1.34851473, 0.20500576, 3.59920244, 0.05944025],
        [1.        , 1.        , 1.        , 1.        ]],

       [[0.27728008, 0.34926733, 1.44382683, 2.12008267],
        [0.84206811, 0.3909853 , 3.08937013, 0.66746445],
        [0.97945481, 0.49459849, 3.18511958, 0.47003919],
        [1.40719988, 0.3335148 , 3.54189653, 2.68201261],
        [0.36243357, 0.37792133, 3.6381877 , 2.69962016],
        [0.35661596, 0.44442165, 2.00202057, 0.55289329],
        [0.06653715, 0.0432124 , 3.48046896, 0.39913318],
        [0.86817136, 0.98861233, 0.11586043, 0.89937261]],

       [[0.80005926, 0.8551943 , 0.04574103, 0.54809041],
        [1

In [2]:
env = TradingEnv('data', commission=0.01, steps=750, start_date_index=0)
env = env_wrapper(env)

In [9]:
env.step(np.array([0, 10, 2, 0, 55, 0, 0, 0]))[0]['action']

array([4.27230414e-05, 9.41037611e-01, 3.15682950e-04, 3.84507373e-04,
       5.70659539e-02, 3.84507373e-04, 3.84507373e-04, 3.84507373e-04])

In [33]:
a = softmax(np.array([0, 0, 0, 0, 0, 0, 0, 0]))
a = np.concatenate([a[:3]*0.1, a[3:]*0.9])
(a / a.sum())

array([0.02083333, 0.02083333, 0.02083333, 0.1875    , 0.1875    ,
       0.1875    , 0.1875    , 0.1875    ])

array([0.01840864, 0.01132587, 0.01046812, 0.12739284, 0.06305695,
       0.14455485, 0.14063896, 0.06253275])