In [9]:
import os
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from networks.model import TD3_Actor
from environment.env import TradingEnv
from pykalman import KalmanFilter
from sklearn.preprocessing import MinMaxScaler
from environment.wrappers import env_wrapper
import matplotlib.pyplot as plt
from scipy.special import softmax

In [37]:
env = TradingEnv('data', commission=0.01, steps=750, start_date_index=0)
env = env_wrapper(env)

In [42]:
env.step(np.array([0, 1, 0, 0, 0, 0, 0, 0]))[0]['observation']

g:\Code\Python\GitHub\Portfolio-Optimizer\.venv\lib\site-packages\pykalman\utils.py:111: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args = inspect.getargspec(obj.__init__)[0]


tensor([[[ -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798],
         [ -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798],
         [ -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798,
           -0.9798,  -0.9798,  -0.9798,  -0.9798,  -0.9798

In [33]:
a = softmax(np.array([0, 0, 0, 0, 0, 0, 0, 0]))
a = np.concatenate([a[:3]*0.1, a[3:]*0.9])
(a / a.sum())

array([0.02083333, 0.02083333, 0.02083333, 0.1875    , 0.1875    ,
       0.1875    , 0.1875    , 0.1875    ])

array([0.01840864, 0.01132587, 0.01046812, 0.12739284, 0.06305695,
       0.14455485, 0.14063896, 0.06253275])