In [2]:
import numpy as np

In [34]:
test = np.empty([1000, 4, 10, 30], dtype=np.float32)

In [11]:
a = {"1":np.random.random([4, 10, 30]), "2":np.random.randn(11)}

In [8]:
np.stack((1, False, np.random.randn(8)))

ValueError: all input arrays must have the same shape

In [35]:
for i in range(len(test)):
    test[i] = a['1']

In [39]:
test[1:].shape

(999, 4, 10, 30)

In [43]:
np.expand_dims(a['1'], axis=0).shape

(1, 4, 10, 30)

In [44]:
np.concatenate([test[1:], np.expand_dims(a['1'], axis=0)]).shape

(1000, 4, 10, 30)

In [18]:
np.delete(test, 0).shape

(1199999,)

In [20]:
test = np.append(test, a['1'])

In [22]:
test

array([0.99089539, 0.05227216, 0.13368036, ..., 0.98197047, 0.87037951,
       0.60166467])

In [32]:
indices = np.random.randint(50, size=64)

In [33]:
np.clip(indices, a_min=1, a_max=50)

array([10, 16, 31, 17, 11,  8,  7, 19, 38, 41,  3, 10, 38, 41,  6, 35, 20,
       29, 16, 13,  5, 32, 32,  7, 12,  7, 23, 49,  2, 41, 17, 31, 27, 48,
       44, 42, 19, 48, 24,  1, 43, 23, 21, 10, 27, 36,  5, 48,  1,  9, 12,
        8, 41, 32, 19,  5, 23, 34, 30, 11, 13,  3,  5, 20])

In [30]:
indices

array([14, 12, 30, 12, 20,  6, 11, 26, 47, 19, 27, 44, 24,  8, 29,  6, 28,
       37, 33, 45, 49, 40, 12, 16, 17, 21, 19,  5, 20,  7, 30, 26, 37, 33,
       43, 10, 12, 48, 47, 17, 39, 10, 11, 41, 44, 33, 24, 46, 14, 22,  5,
       39, 44, 40, 31,  7, 23, 48,  0, 35, 37, 26, 44, 24])

In [45]:
import random
random.randint(0, 16)

13

In [46]:
np.random.randint(0, 16)

12

In [48]:
def test_func(*transitions):
    print(*transitions)

In [49]:
test_func(1, 2, 3)

1 2 3
